### ISSUE TITLE
Units in Metadata

### ISSUE THREAD

**Issue by rgieseke** [Open-Power-System-Data/time_series#11]
Units in the JSON Table Schema are discussed here:

https://github.com/frictionlessdata/specs/issues/216

Maybe it would be useful to include them already as

```json
"unit": "MW"
```
etc.

This would make it easier to do unit conversions automatically.

**Comment by jgmill** [comment]
thanks .this is now implemented: http://data.open-power-system-data.org/time_series/2017-07-09/
