### ISSUE TITLE
Error in timeseries filtered

### ISSUE THREAD

**Issue by Nhubbers** [Open-Power-System-Data/time_series#13]
when I filter  for a LOAD subset, it seems that , "solar_DE-transnetbw_generation" is included in the comment of some rows, causing an extra column somehow. 

As illustrated in the following two sequent example rows: 
2014-03-11T20:00:00Z,2014-03-11T21:00:00+0100,,10397,64166,,57309,43391,3863,798,13887
2014-03-11T21:00:00Z,2014-03-11T22:00:00+0100,"solar_DE-transnetbw_generation",10420,60310,,59936,39560,3595,787,12698

**Comment by jgmill** [comment]
thanks for pointing this out, and sorry for slow response.

This is actually supposed to be not a bug but a feature: The column "interpolated values" specifies which values in a row are missing in the original data AND have been interpolated.
