### ISSUE TITLE
Spain Solar production is wrong 

### ISSUE THREAD

**Issue by robingirard** [Open-Power-System-Data/time_series#25]
While reading your file for date "2016-05-02 12:00:00 UTC" country ES (spain) and techno= Solar I got 5792 (more than the installed capacity in Spain actually). While ENSTOE's data portal shows something around 1645. 

It seems you are not using exactly the ENTSOE data, and maybe you include both solar PV and Solar thermal ?

**Comment by jgmill** [comment]
Hi Robin,

I just checked: [ENTSO-E Transparency shows exactly 5792 MW](https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=02.05.2016+00:00|UTC|DAYTIMERANGE&dateTime.endDateTime=02.05.2016+00:00|UTC|DAYTIMERANGE&area.values=CTY|10YES-REE------0!CTY|10YES-REE------0&productionType.values=B16&dateTime.timezone=UTC&dateTime.timezone_input=UTC) as well. This is below total installed capacity in 2016 which was [6500 MW](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2016+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2016+00:00|UTC|YEAR&area.values=CTY|10YES-REE------0!BZN|10YES-REE------0&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19). You are right though that these values do not distinguish Solar PV from CSP.

Which data source are you using?
